### ISSUE TITLE
Web server configuration

### ISSUE THREAD

**Issue by Dragnucs** [devfake/flox#1]
Please provide sample web server configuration or hints how to set it up.

**Comment by devfake** [comment]
What do you mean with web server configuration? 

There is an `web.config` for ISS (I will add them later to flox): 
https://github.com/laravel/laravel/blob/master/public/web.config

Here is an good Tutorial for nginx:
https://www.digitalocean.com/community/tutorials/how-to-install-laravel-with-an-nginx-web-server-on-ubuntu-14-04

**Comment by Dragnucs** [comment]
By server configuration, I mean what are consideration to take when installing on root domain or in sub folder and how it will impact the `backend/.env` file.

**Comment by devfake** [comment]
It doens't matter in how many subfolders you put flox. Nothing will impact the `.env`  file if you have the `public` and `backend` folder on the same level.

``` bash
# Therefor you need set the CLIENT_URI in .env to '/subfolder/for/flox/public'
http://mydomain.com/subfolder/for/flox/public

# If you map your domain directly to public. Here is CLIENT_URI only '/'
http://mydomain.com
```

Is still somewhat unclear? (:

**Comment by Dragnucs** [comment]
Thank you. I will give you directions a try and get back to you.
