### ISSUE TITLE
Anime Missing

### ISSUE THREAD

**Issue by Sylk** [devfake/flox#108]
There appears to be no anime based titles in this anymore, suggestions on how to fix it?

**Comment by devfake** [comment]
Hey,

could you be a little more specific? Can you name a few titles? Are you getting results for movies?

**Comment by Sylk** [comment]
Hmm, it appears that was due to my own miss-understanding. I thought there were supposed to be titles already populated inside of this and that there was no manual intervention with the data.

**Comment by Sylk** [comment]
Perhaps it would be useful to implement a scraper for some data though? We could have a more complete listing.

**Comment by devfake** [comment]
The TMDb data is relatively up-to-date and complete. I didn't want flox to be filled with informations either.
