### ISSUE TITLE
Issues with migration

### ISSUE THREAD

**Issue by rdgout** [devfake/flox#11]
I noticed with the latest version that apparently we need to reset the migration, rather than the table being expanded with the new fields.
Could you do this for the next release(s) so I (and others) don't have to reset my entire database?
I also noticed that the application doesn't work correctly since there is no created_at field in the episodes table, which you use with the query to get recent items.

I manually fixed these in my database but a more elegant solution should be made!
Great work on this so far!

**Comment by devfake** [comment]
Aye, thank you! My fault with the migrations :| I had planned that before anyone made an update of flox, the database needs to be exported in the settings. After the update it can simply imported again. I will change that in next releases :)

But what do you mean with application doesn't work correctly? I don't use the `created_at` field in episodes nor items. I order them by `id`.

**Comment by rdgout** [comment]
I run flox locally on flox.app. When I use 'last seen' as the sorting type the URL used to fetch the items is: `http://www.flox.app/api/items/tv/created_at`
In this case `created_at` is also the way eloquent tries to sort. However, the tv table doesn't have a `created_at` field!

Also regarding the migration, it might be better practice to create a migration that expands your previous table, there shouldn't be a need to export/import then!

**Comment by devfake** [comment]
There isn't an `tv` table. Movies and TV Shows are in the same `items` table with different `media_type`. So there couldn't be problems with the sort. However, i will push an migration for `created_at` field for the `episodes` table. Just in case :)

I currently looking for a better method to update flox easier without `git fetch` or something.
