### ISSUE TITLE
how to login admin? 

### ISSUE THREAD

**Issue by rimer10** [devfake/flox#112]
i install but i cont find any logins

**Comment by Ghost173** [comment]
same i issue for me in bottom of page there mo option for login

**Comment by devfake** [comment]
Hey!

The login should be at the bottom of the page. Can you both access the `/login` route? Can you send me an email with the url of your flox to devfakeplus@googlemail.com?

**Comment by Ghost173** [comment]
wait ill share

**Comment by Ghost173** [comment]
@devfake  check your mail ill send all details there

**Comment by devfake** [comment]
Can you send me an email again? Thank you!
