### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by wisewtf** [devfake/flox#113]
Hello,

I'm relatively new to this whole Linux world... I managed to install everything correctly (I assume) on my DietPi (Obviously running on my RPi3) created database on MySQL (MariaDB) and I managed to make the software connect to it, created the API and everything but I really can't figure out how to access the web page?

I have the CLIENT_URI set as /flox so I'm assuming I'll have to do localhost/flox to access the web page but that seems like it doesn't work... on the github page an "8888" port is mentioned, unfortunately I have another service running on that port and I can't seem to figure out how to change that port from the default one (if it's actually needed)

Am I missing something?

**Comment by wisewtf** [comment]
EDIT:

I'm inside the nginx.conf and as I thought it is actually listening to the standard HTTP port, the other problem is, I can't access the web page from my http://localhost address, do I need to restart anything if I change the page path to something else? /flox

**Comment by devfake** [comment]
Hey, can you send me an email to devfakeplus@googlemail.com?
