### ISSUE TITLE
Database on separate host

### ISSUE THREAD

**Issue by deranjer** [devfake/flox#12]
Not familiar with artisan/laraval, but I assume it should be easy to change the init script to add a question for "DB_HOST" for those of us with MYSQL running on a separate host?  I added the "DB_HOST=192.168.1.1" line to my .env file manually but might be something you could add to the install process.

**Comment by deranjer** [comment]
I just realized that adding the DB_HOST may break the installation entirely... suddenly get 404 errors on the homepage that I think are caused by my DB_HOST changes.  Any way this will work with a remote mysql database?

**Comment by devfake** [comment]
I don't have any experience with that :| Maybe this can help you?

```
Firewall Block, the server with the MySQL service may be behind a firewall 
that is set to block eternal access to the port that MySQL operates on

MySQL User Permissions, if the MySQL service is not sat behind a firewall 
then the next cause may be that the user has only localhost access permissions
```

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-remote-database-to-optimize-site-performance-with-mysql

**Comment by deranjer** [comment]
Hmm, don't think it has anything to do with that.  When I added the DB_HOST parameter it connected to my database instance just fine and created the database.  However, when I load the homepage I get some 404 errors like this:

http://*******.duckdns.org:8090/flox/public/api/settings Failed to load resource: the server responded with a status of 404 (Not Found)
http://*******.duckdns.org:8090/flox/public/api/items/undefined/created_at Failed to load resource: the server responded with a status of 404 (Not Found)


The API directory obviously does not exist in Public, but the database has tables for both ITEMS and SETTINGS, which made me assume it was trying to read/write to the database, but wasn't expecting it to be hosted at a separate IP address.

**Comment by devfake** [comment]
Can you add me in skype? `pyxl0123` or send me an email to `devfakeplus@googlemail.com`.
