### ISSUE TITLE
Adding Items with releasedate earlier than 1970-01-01 fails.

### ISSUE THREAD

**Issue by crono** [devfake/flox#131]
Hi, 

try adding "Asterix der Gallier" - it will fail with: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1968-12-16 20:52:25' for column 'released_timestamp' at row 1

The problem is: 
> MariaDB stores values that use the TIMESTAMP data type as the number of seconds since '1970-01-01 00:00:00' (UTC). This means that the TIMESTAMP data type can hold values between '1970-01-01 00:00:01' (UTC) and '2038-01-19 03:14:07' (UTC). 
see: https://mariadb.com/kb/en/timestamp/

To fix it, you can change from `timestamp` to `datetime` - find a migration a attached.
[2020_01_09_210708_change_released_timestamp_to_datetime.txt](https://github.com/devfake/flox/files/4042533/2020_01_09_210708_change_released_timestamp_to_datetime.txt)

**Comment by devfake** [comment]
Many thanks for this. Learned something new again :)

Would you mind creating a Pull Request?

**Comment by crono** [comment]
Done - hope it works, it is my first pull request on github :-)
