### ISSUE TITLE
TV shows and movies get mixed up

### ISSUE THREAD

**Issue by ghost** [devfake/flox#137]
If a TV show and a movie have the same id on TMDB and you add one of them to as watched, you are unable to add the other item with the same id.

Tested with the following items:

Sabrina the Teenage Witch [TV Show]: https://www.themoviedb.org/tv/605-sabrina-the-teenage-witch
The Matrix Revolutions [Movie]: https://www.themoviedb.org/movie/605-the-matrix-revolutions

The items show up right in the search, but if you interact with them, they are transforming to the element already in the database.

**Comment by devfake** [comment]
Hey, thank you to pointing this out! I wasn't aware that the ID is not unique at all. Will try to fix this by tomorrow :)

**Comment by ghost** [comment]
I've long used this [app](https://github.com/dmtrbrl/tmdb-app) (albeit in a heavily self-modded version) and experienced exactly the same situation with the both mentioned items. Before that I wasn't aware of this fact too :)

Thanks for your effort!

**Comment by devfake** [comment]
It's fixed now! Thank you again :)
