### ISSUE TITLE
Support for view timestamps

### ISSUE THREAD

**Issue by theryecatcher** [devfake/flox#138]
Thanks a ton for the awesome work. :+1: 

I am unsure of the whole architecture of the app. But was just wondering if the app could have support for timestamps (time and date of the view/rating). Not sure if it's a general requirement but I like to see when and how many times I have viewed a particular episode or a movie just for stat nerds :). I currently use trakt exclusively for this and was looking to replace that with a self hosted service.

**Comment by devfake** [comment]
Thank you very much first :)

We had this idea from the beginning. However, somehow this was never implemented. Basically it is not such a big effort to implement this. But it would first have to be worked out how and where to look at this data.

I will leave this issue open for now and see when I have time to think about it :)

**Comment by theryecatcher** [comment]
Thankyou !! Will look forward to it. Am not well versed with php or could have contributed to do so. :)

**Comment by devfake** [comment]
Sorry for the late response here. I will be completely redeveloping Flox and will add these features :)
