### ISSUE TITLE
Add TMDB release dates for all (or customizable) types to calendar

### ISSUE THREAD

**Issue by AndLindemann** [devfake/flox#142]
TMDB offers multiple "release date" types, like cinema, physical, TV etc.
Currently I believe only the cinema release date is shown on the calendar.
Can we add other types as well? Maybe even able to select which ones to show in the calendar?

It's available through their API, so data should be easy to retrieve.

https://developers.themoviedb.org/3/movies/get-movie-release-dates

**Comment by devfake** [comment]
Thanks for the idea. I have currently not so much time to develop such bigger things. I leave this issue open for now :)

**Comment by devfake** [comment]
Closed because i will be completely redeveloping Flox.
