### ISSUE TITLE
Delete item?

### ISSUE THREAD

**Issue by AndLindemann** [devfake/flox#144]
I can, even after solid searching most pixels of the interface, not find a delete button to remove added media from Flox. Anyone have a screenshot of where to find it, if it's there? :)

**Comment by devfake** [comment]
Sorry for the late response. Are you logged in? On the subpage under the poster is a link button to delete the show.

![Unbenannt](https://user-images.githubusercontent.com/2204770/74058082-88d1a300-49e5-11ea-9ec1-3d8a4a210692.PNG)

**Comment by AndLindemann** [comment]
Yes, logged in. I can certainly say, I do not have these buttons. Will get you a screenshot when I‘m back later.

**Comment by devfake** [comment]
If you are on mobile? Then you need to scroll down to after the summary text.

**Comment by AndLindemann** [comment]
Both mobile and desktop do not show the buttons.
<img width="777" alt="Bildschirmfoto 2020-02-07 um 21 40 15" src="https://user-images.githubusercontent.com/4157845/74064240-8b86c500-49f2-11ea-9889-cf7bb09db8d8.png">
![IMG_0E40A74897E9-1](https://user-images.githubusercontent.com/4157845/74064364-cd177000-49f2-11ea-847c-8d1446e1d52b.jpeg)

**Comment by exane** [comment]
Well that's because you did not add the media at all. 

You can only "delete" media that you actually have added (i. e. clicking on that big plus sign).
That leads me to believe that we might have a misunderstanding between what you mean with "deleted media" and what we understand of it.

Could you explain your use case a bit more detailed? 
I think what you are looking for is a sort of "exclude" or "hide" feature for media you are not interested in? If that's the case then no, that is not yet implemented.

**Comment by AndLindemann** [comment]
That media was added automatically through the Plex API.
It is also rated (when on the Overview screen, see below). However when I go to the detail screen, it does show the "+" button, instead of the rated thumb-up.
So, when it is added through the Plex API - shouldn't it actually be "added"? Because otherwise, what do we have the API for?
Nevertheless, at least when I actually rate it, it should then of course be added, because otherwise from a use-case perspective, it wouldn't make sense at all. :) 

<img width="675" alt="Bildschirmfoto 2020-02-08 um 10 49 51" src="https://user-images.githubusercontent.com/4157845/74083204-9dec1780-4a61-11ea-86c2-3d470fbd1d52.png">
<img width="688" alt="Bildschirmfoto 2020-02-08 um 10 50 02" src="https://user-images.githubusercontent.com/4157845/74083206-a04e7180-4a61-11ea-8f9f-6abe13617d04.png">

**Comment by exane** [comment]
Yep, that looks like an oversight. Thanks for your help figuring that out. 👍

**Comment by devfake** [comment]
Thanks a lot for your help. The problem had nothing to do with the Plex API feature, it was a mistake of mine. Should work now :)
