### ISSUE TITLE
Add short notes to media items

### ISSUE THREAD

**Issue by AndLindemann** [devfake/flox#145]
It'd be nice if we could add short notes to items while on the detail media screen.
The wife asked for this, just so that she can add short remarks to an item.
Guess a simple text field would do, 3-4 lines, just to add some quick additional data like for items that she liked and I didn't or so.

**Comment by devfake** [comment]
This idea was also initially planned. But like #138 somehow this was never implemented. It would be good if we could add more meta data. For example when you actually saw the movie.

I will also leave this issue open for now.

**Comment by JesseWebDotCom** [comment]
+1, Notes would turn this app from useful to priceless!  Is there any chance of getting this added?

**Comment by devfake** [comment]
Sorry for the late response here. I will be completely redeveloping Flox and will add these features :)
