### ISSUE TITLE
Set default queue driver to database

### ISSUE THREAD

**Issue by AndLindemann** [devfake/flox#146]
Most people probably don't have a running Redis at hand and installing one just for the Laravel queue of Flox seems a bit oversized.
I believe we can set the default queue driver to database in backend/.env?
The DB table for the queue is already created during the installation, so there should not be any additional steps necessary. At least it seems to work fine here.

**Comment by devfake** [comment]
You're right. I was a little worried about deadlocks. But I haven't noticed any problems with it so far.
