### ISSUE TITLE
Suggestions and view progress buttons disappear on small screens

### ISSUE THREAD

**Issue by d-Rickyy-b** [devfake/flox#149]
Hi there, awesome project!

I just played a bit around with it and found that when using smaller screens, the buttons for the suggestions and for the view progress will simply disappear so that you can't track your progress from a mobile phone for example. Maybe the buttons also just move to somewhere else, but I simply can't find them. Would appreciate an answer and if applicable a fix for this 😊. Thank you!

### Large screens
![grafik](https://user-images.githubusercontent.com/5798157/74375441-9a012200-4de0-11ea-876f-97e824d72dcc.png)

### Small screens
![grafik](https://user-images.githubusercontent.com/5798157/74375479-ae451f00-4de0-11ea-809c-9f54b6cb87aa.png)

**Comment by devfake** [comment]
Hey, thanks a lot for the report! I will of course fix it as soon as possible :)
