### ISSUE TITLE
Site Loads but no Content - Linux Install

### ISSUE THREAD

**Issue by mitchelnieto** [devfake/flox#151]
Hello,

Does anyone have this project working on a Linux system? I have tried Debian (v9 & 10) and Ubuntu (18.04 & 19.10), both as containers and VMs and have been unable to load any movies on the site. I can see the site but they 'eye' icon just blinks. I am using Apache2, MySQL, and PHP.

What flavor of Linux are you using to get this project running?

Thanks,
Mitch

**Comment by devfake** [comment]
Sorry, I didn't see this issue.

Do you still have that problem? Can you open the browser console and see what error you get from the network request?
