### ISSUE TITLE
Setting up Flox with SQLite

### ISSUE THREAD

**Issue by Itchyfantastico** [devfake/flox#152]
I try to deploy flox on my Raspberry Pi with sqlite.

However, the database doesn't get filled, the db file stays empty even though the "php artisan flox:db" command outputs "MIGRATION COMPLETED".

I followed the instructions on [https://laravel.com/docs/6.x/database](https://laravel.com/docs/6.x/database) and those on this site.
The webserver is Apache2 on a debian based linux (OSMC).

This is my .env:
```
TMDB_API_KEY=apikey
TRANSLATION=DE

CLIENT_URI=/flox/public
LOADING_ITEMS=30

# Default 10 minutes (600 seconds)
PHP_TIME_LIMIT=600

# Set your correct timezone
TIMEZONE=UTC

# Date pattern for reminder mails
DATE_FORMAT_PATTERN=d.m.Y

DAILY_REMINDER_TIME=10:00
WEEKLY_REMINDER_TIME=20:00

DB_CONNECTION=sqlite
DB_HOST=
DB_PORT=
DB_DATABASE=/var/www/html/flox/backend/database/database.sqlite
DB_USERNAME=
DB_PASSWORD=

APP_URL=http://osmc
APP_ENV=local
APP_KEY=appkey
APP_DEBUG=true

APP_LOG=daily
QUEUE_DRIVER=database

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

Thank you for any input in advance!

**Comment by devfake** [comment]
Many thanks for the report :)

The problem was, that `DB_DATABASE` in the env had no impact to the sqlite config. I fixed it!

**Comment by Itchyfantastico** [comment]
Great, thank you very much for sharing this project and fixing the bug! :)
