### ISSUE TITLE
Watched episodes are not saved

### ISSUE THREAD

**Issue by Itchyfantastico** [devfake/flox#153]
I can add TV shows, but the selection of watched episodes doesn't get saved in my installation.
I am using Apache2 and SQLite as db.

After reloading the page the TV show reverts back to this:
![Flox Bug](https://user-images.githubusercontent.com/60258928/76249490-b9eefe80-6243-11ea-9941-db490d564021.jpg)

Thank you in advance for looking into it!
Let me know if I can upload a log.

**Comment by devfake** [comment]
Hey, is the problem still there?
