### ISSUE TITLE
Flox fails if openssl-1.1.1.e-1 is installed

### ISSUE THREAD

**Issue by ghost** [devfake/flox#155]
If openssl is installed with the version 1.1.1.e-1, Symfony fails with the following error:

SSL routines:ssl3_read_n:unexpected eof while reading at /usr/share/nginx/flox/backend/app/Services/Storage.php:39 (https://github.com/openssl/openssl/pull/10882)

This breaks some of the functionality of flox, e.g. the image retrieval...

**Comment by devfake** [comment]
Hey, is the problem still there?

**Comment by ghost** [comment]
The problem is gone! :)
