### ISSUE TITLE
Synology web server - site loads, nothing works, blinking eye icon

### ISSUE THREAD

**Issue by AlexFullmoon** [devfake/flox#161]
Browser console gives me "Error: Request failed with status code 404 vendor.js:17:36334". Not sure how to get more debug information. Server runs on Nginx and PHP 7.2.

This is probably related to something misconfigured, perhaps in built-in PHP in Synology — it is quite... limited. Installation went without errors, though. Should I provide phpinfo output?

Hm. Docker image from theryecatcher/flox fork works. But it is an additional overhead.

I understand that this is an edge case, sorry.

**Comment by rodgersan** [comment]
Hi,

Sorry for the useless post but I wish flox was "more" maintained and supported as easy packages to install on NAS. That would be great to replace trakt.tv. It is already for me pretty much difficult to run on a linux machine (Fedora 33). 
@AlexFullmoon, have you managed to make it work on your NAS?

Regards,

**Comment by AlexFullmoon** [comment]
Actually, yes. I run it in Docker, using [theryecatcher/flox](https://github.com/theryecatcher/flox) fork, and building docker image locally — there might be some other changes in that fork.

The fix is forcing https on things that might try loading via http. Mainly scripts. I still sometimes get broken images though.
```
diff --git a/backend/app/Providers/AppServiceProvider.php b/backend/app/Providers/AppServiceProvider.php
index 35471f6..31813e6 100644
--- a/backend/app/Providers/AppServiceProvider.php
+++ b/backend/app/Providers/AppServiceProvider.php
@@ -3,6 +3,7 @@
 namespace App\Providers;
 
 use Illuminate\Support\ServiceProvider;
+use Illuminate\Support\Facades\URL;
 
 class AppServiceProvider extends ServiceProvider
 {
@@ -13,7 +14,8 @@ class AppServiceProvider extends ServiceProvider
      */
     public function boot()
     {
-        //
+       $this->app['request']->server->set('HTTPS', true);
+       URL::forceScheme('https');
     }
 
     /**
@@ -23,6 +25,8 @@ class AppServiceProvider extends ServiceProvider
      */
     public function register()
     {
-        //
+        if (env('APP_ENV') === 'production') {
+           $this->app['request']->server->set('HTTPS', true);
+        }
     }
 }

diff --git a/public/.htaccess b/public/.htaccess
index 903f639..9ccd6c9 100644
--- a/public/.htaccess
+++ b/public/.htaccess
@@ -4,6 +4,10 @@
     </IfModule>
 
     RewriteEngine On
+	RewriteCond %{HTTPS} !=on
+    RewriteCond %{HTTP:X-Forwarded-Proto} .
+    RewriteCond %{HTTP:X-Forwarded-Proto} !https
+    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
 
     # Redirect Trailing Slashes If Not A Folder...
     RewriteCond %{REQUEST_FILENAME} !-d
```

**Comment by rodgersan** [comment]
> Actually, yes. I run it in Docker, using [theryecatcher/flox](https://github.com/theryecatcher/flox) fork, and building docker image locally — there might be some other changes in that fork.
> 
> The fix is forcing https on things that might try loading via http. Mainly scripts. I still sometimes get broken images though.
> 
> ```
> diff --git a/backend/app/Providers/AppServiceProvider.php b/backend/app/Providers/AppServiceProvider.php
> index 35471f6..31813e6 100644
> --- a/backend/app/Providers/AppServiceProvider.php
> +++ b/backend/app/Providers/AppServiceProvider.php
> @@ -3,6 +3,7 @@
>  namespace App\Providers;
>  
>  use Illuminate\Support\ServiceProvider;
> +use Illuminate\Support\Facades\URL;
>  
>  class AppServiceProvider extends ServiceProvider
>  {
> @@ -13,7 +14,8 @@ class AppServiceProvider extends ServiceProvider
>       */
>      public function boot()
>      {
> -        //
> +       $this->app['request']->server->set('HTTPS', true);
> +       URL::forceScheme('https');
>      }
>  
>      /**
> @@ -23,6 +25,8 @@ class AppServiceProvider extends ServiceProvider
>       */
>      public function register()
>      {
> -        //
> +        if (env('APP_ENV') === 'production') {
> +           $this->app['request']->server->set('HTTPS', true);
> +        }
>      }
>  }
> 
> diff --git a/public/.htaccess b/public/.htaccess
> index 903f639..9ccd6c9 100644
> --- a/public/.htaccess
> +++ b/public/.htaccess
> @@ -4,6 +4,10 @@
>      </IfModule>
>  
>      RewriteEngine On
> +	RewriteCond %{HTTPS} !=on
> +    RewriteCond %{HTTP:X-Forwarded-Proto} .
> +    RewriteCond %{HTTP:X-Forwarded-Proto} !https
> +    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
>  
>      # Redirect Trailing Slashes If Not A Folder...
>      RewriteCond %{REQUEST_FILENAME} !-d
> ```

That seems already good. Yet Docker seems far beyond my skills. Can't go even past the ./env setup.

Hope someone will take over flox development. Anyway thanks for your answer!

**Comment by devfake** [comment]
Hey, sorry for the late response. I will be completely redeveloping Flox and will add Docker support. So that such issues should hopefully not occur.
