### ISSUE TITLE
Release dates for each langue / country (preferred way IMDb)

### ISSUE THREAD

**Issue by ex0nuss** [devfake/flox#162]
Hi,

Your app is really handy and beautiful. I finished setting up the webpage. After adding the first movies, which I would like to see in theaters, I noticed a problem regarding release dates.

### Situation

In the .env-File I set the language to DE since I life in Germany. I watch most of the movies and TV shows in English but it's handy to get the German title. This works great!

But the flox-calendar is still using the international release dates.

### Example where this results in a problem:
Most of the movies in Germany are getting released at Thursdays but in the USA at Fridays.

### Seccond example:
The movie "Richard Jewell" was delayed in Germany due to Covid-19 and is now getting released at the **2nd of July**.
In the Flox-Calendar-tab it's shown for the **13th of December 2019** since that's what the TMDb says.

When I manually query the TMDb-API is says **2020-03-19** for Germany. Since the TMDb is maintained by the community the release dates might not be correct.
```
        {
            "iso_3166_1": "DE",
            "release_dates": [
                {
                    "certification": "12",
                    "iso_639_1": "",
                    "note": "",
                    "release_date": "2020-03-19T00:00:00.000Z",
                    "type": 3
                },
                {
                    "certification": "12",
                    "iso_639_1": "",
                    "note": "",
                    "release_date": "2020-08-06T00:00:00.000Z",
                    "type": 5
                }
            ]
        }
```
_Type 3 is cinema-release, type 5 blueray_

When using the **IMDB** it will always show the correct release date.
If using the IMDB is not possibly, it would be nice to have the option to **manually edit the release date** in the Flox-calendar for correcting dates.

Thank you in advance for you help.
Regards :)

**Comment by devfake** [comment]
Hey, sorry for the late response. I will close this issue because i will completely redevelop Flox. In the next version, i will include something like this! :)

**Comment by ex0nuss** [comment]
No worries and have fun devolving it ;) I am excited to see more!
