### ISSUE TITLE
Error in searchTMDB(): Error: Request failed with status code 422

### ISSUE THREAD

**Issue by mitchelnieto** [devfake/flox#163]
Hello,

This is really a great project and I have been looking forward to getting this setup on my network. The server is running and it pulls down movies from Trending/Popular/Upcoming, but all of my searches return error 422.

TMDB API Status Code:
5 | 422 | Invalid parameters: Your request parameters are incorrect.

Not sure if anyone else is seeing this error.

Do you have any ideas on a resolution for this?

Thank you again for Flox!

**Comment by devfake** [comment]
Hey, sorry for the late reply. Hopefully you were able to solve the problem? Off the top of my head, unfortunately, I do not know exactly what the problem could be.
