### ISSUE TITLE
No Content, Eye 

### ISSUE THREAD

**Issue by MaximilianGT500** [devfake/flox#166]
/api is missing

![Screenshot_2](https://user-images.githubusercontent.com/49883584/89134859-d8be9c00-d528-11ea-93d7-a8a4ae74158a.png)
![Screenshot_1](https://user-images.githubusercontent.com/49883584/89134861-d9efc900-d528-11ea-9597-ce7ca197f2a8.png)

**Comment by adetheprince** [comment]
Me Too 
Is this normal because I have not added movies , shows etc? Not even a footer or any links
But where is settings? I cant see any thing, I see just like this screen, can you help us please?

**Comment by FloPrey** [comment]
I had the same issue, seems to be a rewriting problems for the routes of laravel.
For me it works with adding a .htaccess file to the main directory, as described in https://laravel.com/docs/6.x/installation#pretty-urls

Hope that helps.
@devfake would be probably cool to add this to the description, as I am the third person having this issue.

Greets,
Flo

**Comment by MaximilianGT500** [comment]
Yea fixed i see i deleted the .htaccess files

**Comment by Devilshz** [comment]
@FloPrey & @MaximilianGT500  I tried modifying the .htaccess following https://laravel.com/docs/6.x/installation#pretty-urls and tried deleting the whole file but same issue is there, is there anything i am missing ? 

I am using Apache php 7.4 with MariaDB.
