### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by sukhmeet2729** [devfake/flox#172]
I used the project and liked it very much but there are some things that are still needed in this project.
1. Multi user support - This issue was also discussed earlier but still it would be nice if users can register and login, they can see like history of shows they've visited and rate them. I would like to say that the 3 way rating system is not good, if users can register they should be able to give ratings like numbers or stars like 4.5/5.
2. Favorites - Right now there is a watchlist feature but i don't understand the practical use for it, i mean admin can add shows to watchlist but they are automatically removed when posted. Instead this i would like to suggest Favorites feature where each user can add or delete shows from their favorite list.
3. Download or stream system - Everything aside what could be the practical usage of this project, i only think of a movie/shows/anime downloading or streaming website. So, it would be nice if admin can add download or stream links to partical movie or show(They could be added dynamically like admin can add a number of download buttons and even rename each one of them).
4. Views - If some one use this website, it will be helpful if he had some stats like total website views in past specific time or number of views of each movie/show.
5. Create own genre - Genres are fetched from TMDB but admin should also be able to add/update/remove custom genres. Like if a show is ongoing i would like to add ongoing tag/genre to it(By the way i liked that ongoing shows are showing in the calendar, it's a good idea).
I mean i liked the project very much but these are just my suggestions to make it even greater.

**Comment by devfake** [comment]
Hey, sorry for the late response. Thank you very much for your input!

I will close this issue because i will completely redevelop Flox.
