### ISSUE TITLE
FEATURE REQUEST: Plex alert when new episode is available

### ISSUE THREAD

**Issue by JesseWebDotCom** [devfake/flox#173]
You already have the calendar where we can view the date an upcoming episode airs.  Maybe with a plex webhook you could send an alert when a new episode is available to watch in plex.

**Comment by durnezj** [comment]
That would mean Flox should download the episode or monitor other applications right? That it can't do, and probably shouldn't to keep Flox having the only responsability of just being a watched media tracker.
However I've been successful at notifying me for new episodes by setting up the notifiers of Plex, Ombi, Medusa and Radarr through an email or Discord notification. That way you can notify yourself on every step (episode aired, searching and fetching it and finally available in Plex for you to watch). 

I hope this helped you, I'm an avid user of Flox and wanted to share how I set up my other apps in my ecosystem in regard to your question.

**Comment by devfake** [comment]
Thanks for your help @durnezj here. I will close this issue.
