### ISSUE TITLE
flox/public/login not loading... .env issue?

### ISSUE THREAD

**Issue by digibucc** [devfake/flox#179]
After installing, I can load the public page. it gives an error in the console:

`TypeError: t.items is undefined
    i http://192.168.42.180/flox/public/assets/app.js:1
    _render http://192.168.42.180/flox/public/assets/vendor.js:17
    r http://192.168.42.180/flox/public/assets/vendor.js:12
    get http://192.168.42.180/flox/public/assets/vendor.js:17
    run http://192.168.42.180/flox/public/assets/vendor.js:17
    Ut http://192.168.42.180/flox/public/assets/vendor.js:12
    ct http://192.168.42.180/flox/public/assets/vendor.js:12
    at http://192.168.42.180/flox/public/assets/vendor.js:12
vendor.js:12:12540
    it http://192.168.42.180/flox/public/assets/vendor.js:12
    ot http://192.168.42.180/flox/public/assets/vendor.js:12
    rt http://192.168.42.180/flox/public/assets/vendor.js:12
    _render http://192.168.42.180/flox/public/assets/vendor.js:17
    r http://192.168.42.180/flox/public/assets/vendor.js:12
    get http://192.168.42.180/flox/public/assets/vendor.js:17
    run http://192.168.42.180/flox/public/assets/vendor.js:17
    Ut http://192.168.42.180/flox/public/assets/vendor.js:12
    ct http://192.168.42.180/flox/public/assets/vendor.js:12
    at http://192.168.42.180/flox/public/assets/vendor.js:12
`

additionally, when I click login at the bottom it just brings me to the root of the directory containing the flox folder, and loads the index.php file in that parent directory.

i'm assuming i did something wrong in the .env

**Comment by devfake** [comment]
Hey, sorry for the late reply. Hopefully you were able to solve the problem? Off the top of my head, unfortunately, I do not know exactly what the problem could be.
