### ISSUE TITLE
Document how to reset password for a user

### ISSUE THREAD

**Issue by coalwater** [devfake/flox#186]
I've installed flox on a weekend night, and I was enjoying it for a couple of days, then I've lost my password which was randomly generated from a password manager but it seems I didn't sync it and I lost it.

I wanted to reset the user password, I tried looking into the php console but I didn't find any utilities to change the password.

I would prefer to avoid clearing the whole database and starting from scratch

Is there a way to do that ?

I have flox installed in a vm and using sqlite.

**Comment by coalwater** [comment]
Ok I dug around for how to do user password changes in laravel and here's what I found

First start the php console
```bash
php artisan tinker
```
Then find the user
```php
$user = App\User::where('id', '1')->first();
```
Then change the password
```php
$user->password = Hash::make('your-new-password');
$user->save()
```

Hope this is useful for other users

PS: I can create a PR to add this in the README

**Comment by devfake** [comment]
Thanks for your input. In the next version, i will add a password reset field.
