### ISSUE TITLE
[Feature Request] Search by TMDB ID

### ISSUE THREAD

**Issue by unknown8063** [devfake/flox#189]
Today I wanted to add a film to Flox that had a difficult title to search for. In fact, the film title was only one letter and Flox refused to even process my search request.

I think there are other examples of movies and TV shows that are difficult to search for. Perhaps a simple solution is to allow us to search by the TMDB ID directly. Indeed, I was able to pull up the movie using https://[my flox domain]/movies/[id] and add it my watchlist that way. It would be great if there was a way to find these titles without typing into the URL bar directly.

**Comment by devfake** [comment]
Hey, thank you for this idea. Makes sense :)

I will close this issue because i will completely redevelop Flox. In the next version, i will include something like this!
