### ISSUE TITLE
just curious

### ISSUE THREAD

**Issue by ghost** [devfake/flox#2]
any reason you are not using [php-tmdb/laravel](https://github.com/php-tmdb/laravel) and [algolia/algoliasearch-laravel](https://github.com/algolia/algoliasearch-laravel)

also it would be great if you can implement tmdb [authentication ](https://developers.themoviedb.org/3/authentication)

**Comment by devfake** [comment]
I think there is no reason to use the `algoliasearch-laravel` package if i use `laravel scout` :)
But the api package looks good and i'll write it on my todo list.

I don't have much experience with the tmdb api. Can I read the tmdb data from the user when he is authenticated? Possibly i can add this option with multiuser :)
