### ISSUE TITLE
Shared Hosting Support?

### ISSUE THREAD

**Issue by MichaelTunnell** [devfake/flox#60]
Most shared hosting services don't support Composer so would you be willing to release a package that could be used on a shared hosting service?

**Comment by devfake** [comment]
We are currently working on version 2. With this version we want to make the setup and update of flox easier, especially for shared hosts.

In the meantime, i created a [ZIP](http://80.240.132.120/flox-demo/flox-1.2.2.zip) file which contains all composer dependencies and the sql file to import (with default user of `admin/admin`).

  What you need to do:
  - Download the [ZIP](http://80.240.132.120/flox-demo/flox-1.2.2.zip) file and upload the contents into your webhoster.
  - Give `backend/storage`, `public/assets` and `public/exports` recursive write access from your FTP programm.
  - Import the SQL file `flox_demo.sql`. Typically in phpMyAdmin.
  - Change your database credentials in `backend/.env`.
  - Set your TMDb API-Key in `backend/.env`.
  - Set the correct `CLIENT_URI` in ´backend/.env`. See [readme](https://github.com/devfake/flox#install) of this repo for more informations.
  - On shared hostings you typically need to set the `RewriteBase` in `public/.htaccess`. This is the same value as in `CLIENT_URI` above.

Don't forget to change your website login credentials in the settings page.

  Is something unclear or can we help you with something else? :)

**Comment by MichaelTunnell** [comment]
wow holy crap . . . I did not expect such a response especially not as quickly. :)

Thank you for this and I will test this as soon as possible, thanks again.

**Comment by Gikto** [comment]
Hi, I followed all the instructions but when I go to my website, I have an Error 500 - Internal server error..

I rename the folder 'flox' into 'watchlist' is this the issue ?
