### ISSUE TITLE
Unsecured content to https

### ISSUE THREAD

**Issue by rollecode** [devfake/flox#78]
Hello! First of all, I love your project. As a huge movie-holic it's my dream to build a recommendations engine some day using data from IMDb, TMDb, Trakt, Letterboxd, etc.

But for the issue. My https is not green and I see the images from tmdb are unsecure. Can you update flox to be 100% under http, including assets from outside.

**Comment by devfake** [comment]
Hey!

Sorry for the delayed response. I will change the few TMDb links that are not served under https tomorrow :)
