### ISSUE TITLE
TMDB 500 Error 

### ISSUE THREAD

**Issue by 14ngr15t** [devfake/flox#79]
I finally got Flox up and running just fine, but when I search for anything, click on Trending, etc I get a 500 error returned from TMDB.  I checked their status page and they don't show anything going on that would affect this.  I'm using the version 3 API key.  Any ideas?  

Thanks!

**Comment by devfake** [comment]
Hey,

can you send me an email to devfakeplus@googlemail.com with a public url?

**Comment by exane** [comment]
Could you provide us logs? 
The logs can be found in flox/backend/storage/logs and any detail about the 500 status request would be helpful (header and response body).

**Comment by danielsatanik** [comment]
Hey,

I had the same problem. I wasn't reading properly so I missed that I had to add an API key from TMDB. I don't want to sound presumptuous but maybe you forgot that too.

You just have to sign up at https://www.themoviedb.org/?language=en and then create an API key. They will ask you a few questions. This key you will have to add to the .env file in your laravel installation of flox.
