### ISSUE TITLE
is it possible to input/read movies & tv from a directory / file structure ?

### ISSUE THREAD

**Issue by saveyour** [devfake/flox#8]
for example, if i got: ~/Movies/Example.Movie.2016.bla.bla.bla.mkv in a folder, along with a ton of others, is there a way for Flox to watch this folder and build my movie db from the names of the folders and files inside of it ? 

This feature would make this super useful to me. Anyway, good work keep it up!

**Comment by devfake** [comment]
Thank you :)

That would be possible, but it wouldn't work full automatically. We need to split each word of the file, then the user need to select which word to use for an TMDb search. That would have to be done with every file.

I will write it to my todo-list, but I have to do other things before :)

**Comment by saveyour** [comment]
maybe something like this would help ? 

https://github.com/Ivshti/video-name-parser/blob/master/index.js

**Comment by devfake** [comment]
This looks good :) Will try to use this. Thank you!

**Comment by devfake** [comment]
I just wanted to give you an update: we are working on this feature right now :)

**Comment by netwrkx** [comment]
any luck regarding this feature?

**Comment by exane** [comment]
We're still working on it.
