### ISSUE TITLE
Updates don't work properly

### ISSUE THREAD

**Issue by danielsatanik** [devfake/flox#80]
It seems my installation works half. I can add new series even though I have to reload to make sure they show up and every second time I try to change my ratings I get an error "Error in saveNewRating()".

AND: I cannot load the episode information on the series. It loads and then it stops.

here is my installation: https://flox.satanik.at

**Comment by devfake** [comment]
Hey,

can you send me an email to devfakeplus@googlemail.com with login data for the flox app?

**Comment by danielsatanik** [comment]
I can send you some logs as well if it helps…

**Comment by devfake** [comment]
Problem was the usage of Laravel Scout without provide a value for `SCOUT_DRIVER` in `.env`.
