### ISSUE TITLE
404's with attempted api calls

### ISSUE THREAD

**Issue by 5aji** [devfake/flox#87]
Hi, I just tried to get Flox working on a VPS. It seems that it worked, since I am now presented with the flox main page, however it loads forever because it can't make some API calls for some reason. 
relevant logs:
```
vendor.js:13 GET http://localhost/flox/public/api/settings 404 (Not Found)
(anonymous) @ vendor.js:13
e.exports @ vendor.js:13
e.exports @ vendor.js:13
vendor.js:13 Uncaught (in promise) Error: Request failed with status code 404
    at e.exports (http://localhost/flox/public/assets/vendor.js:13:21191)
    at e.exports (http://localhost/flox/public/assets/vendor.js:13:26983)
    at XMLHttpRequest.p.(anonymous function) (http://localhost/flox/public/assets/vendor.js:13:19950)
e.exports @ vendor.js:13
e.exports @ vendor.js:13
p.(anonymous function) @ vendor.js:13
vendor.js:13 GET http://localhost/flox/public/api/items/home/rating 404 (Not Found)
```

any idea? the call itself is strange, since the public folder is not restful.

I am running on nginx with php7 and mariadb, all stable.

**Comment by devfake** [comment]
Can you check the `CLIENT_URI` in `.env`? Seems you need to edit the path. Or send me an email to devfakeplus@googlemail.com with your url.

**Comment by 5aji** [comment]
`CLIENT_URI` is set to `/flox/public` which makes sense since I dropped the whole repository into my `/var/www/html` folder

**Comment by devfake** [comment]
Can you send me an email?

**Comment by 5aji** [comment]
Sent!

**Comment by 5aji** [comment]
was an issue with nginx root, closing.
