### ISSUE TITLE
Does not rescrape

### ISSUE THREAD

**Issue by PeterXQChen** [devfake/flox#88]
It does not rescrape show details on a scheduled basis or an option to manually rescrape so once added, the seaons/episodes will be outdated. 

Can you please add a manually rescrape or daily auto rescrape feature?

Thanks

**Comment by devfake** [comment]
This feature will be availabe in version 2 :)

**Comment by netwrkx** [comment]
Hello, what's the count down to version 2

**Comment by devfake** [comment]
We are trying to get it finished this year.
