### ISSUE TITLE
Deploying Flox on Ubuntu 

### ISSUE THREAD

**Issue by fazlerabbi37** [devfake/flox#99]
I find this project very interesting and want to deploy it on a home Ubuntu machine but I have very little knowledge about php, composer and nginx. I was able to follow alone up until database migrations. I think I messed up on the CLIENT_URI part as I can't access the site at the CLIENT_URI. Is it possible to make a installation guide for Ubuntu? I am using Ubuntu 16.04. Thanks in advance !

**Comment by devfake** [comment]
Hey,

can you send me an email with your site link to devfakeplus@googlemail.com?

**Comment by fazlerabbi37** [comment]
I am running the on a LAN with a private IP so I don't think that would help much.

**Comment by devfake** [comment]
Have the migrations run successfully? What do you have in CLIENT_URI? Any errors in the console if you access the site?

**Comment by fazlerabbi37** [comment]
`http://localhost:8888/flox/public` that is my CLIENT_URI. 
nginx error:
`[error] 877#877: *2 directory index of "path/to/flox/public/" is forbidden`

**Comment by devfake** [comment]
Hm, unfortunately I don't know much about nginx. Maybe someone else can help :/

**Comment by exane** [comment]
Seems more like an issue with unix permissions than with Flox.

Does your public folder have read access?
You may change the owner of your folder to the current user and see if that helps.
```sh
sudo chown -R $(whoami) /var/www/flox/public
```

If the issue still persists then please share your nginx config.
